## Inheritance-based subclasses
## setClass("ClassRecord", contains = "Record")
## setClass("FactionRecord", contains = "Record")
## setClass("MagicEffectRecord", contains = "Record")
## setClass("ScriptRecord", contains = "Record")
## setClass("DoorRecord", contains = "Record")
## setClass("WeaponRecord", contains = "Record")
## setClass("ContainerRecord", contains = "Record")
## setClass("SpellRecord", contains = "Record")
## setClass("CreatureRecord", contains = "Record")
## setClass("NPCRecord", contains = "Record")
## setClass("ArmorRecord", contains = "Record")
## setClass("ClothingRecord", contains = "Record")
## setClass("ActivatorRecord", contains = "Record")
## setClass("AlchemyApparatusRecord", contains = "Record")
## setClass("IngredientRecord", contains = "Record")
## setClass("AlchemyRecord", contains = "Record")
## setClass("DialogueTopicRecord", contains = "Record")
