## Define the openssl classes we'll be wrapping
setOldClass(c("hash", "sha256"))

## Define our wrapper class
setClass("SHA256Hash",
         contains = c("hash", "sha256"),
         prototype = openssl::sha256(raw(0)))

## Constructor/helper function
SHA256Hash <- function(x) {
  if (inherits(x, "hash")) {
    new("SHA256Hash", x)
  } else if (is.raw(x)) {
    new("SHA256Hash", openssl::sha256(x))
  } else if (is.character(x)) {
    ## If it's a hex string, convert to raw then hash
    if (nchar(x) == 64 && grepl("^[0-9a-fA-F]+$", x)) {
      raw_data <- openssl::hex2raw(x)
      new("SHA256Hash", structure(raw_data, class = c("hash", "sha256")))
    } else {
      ## If it's regular text, convert to raw then hash
      new("SHA256Hash", openssl::sha256(charToRaw(x)))
    }
  } else {
    stop("Input must be a hash object, raw vector, or character string")
  }
}

setGeneric("show", function(x) standardGeneric("show"))
#' @examples
#' \dontrun{
#' hash1 <- SHA256Hash("test")
#' hash2 <- SHA256Hash(charToRaw("test"))
#' }
#'
#' ## The only recommended entry point is the following. The others were
#' ## auto-generated by Shiny Assistant.
#' hash3 <- SHA256Hash(openssl::sha256("test"))
#'
#' \dontrun{
#' hex_string <-
#'   "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
#' hash4 <- SHA256Hash(hex_string)
#' }
## ShinyAssistant, "Inherit openssl methods automatically through contains, but
## we can override or add specific methods if needed."
setMethod("show", "SHA256Hash",
          function(object) {
            cat("SHA256Hash:", openssl::hex2raw(as.character(object)), "\n")
          })

